### P027 乳腺癌数据集 - 加载并认识数据

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
breast_cancer = load_breast_cancer()

In [3]:
print(breast_cancer["DESCR"])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

### P028 查看data和target

In [4]:
data = breast_cancer["data"]
target = breast_cancer["target"]

In [5]:
data.shape

(569, 30)

In [6]:
target.shape

(569,)

In [7]:
type(data), type(target)

(numpy.ndarray, numpy.ndarray)

In [8]:
data[:3]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [9]:
target[:3]

array([0, 0, 0])

### P029 合并data和target到大数组

In [10]:
import numpy as np

In [11]:
data.shape

(569, 30)

In [12]:
target.shape

(569,)

In [13]:
all_datas = np.c_[data, target]

In [14]:
all_datas[1]

array([2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
       8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
       3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
       1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
       1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02,
       0.000e+00])

### P030 乳腺癌数据集 - 生成Pandas的df

In [15]:
import pandas as pd

In [1]:
df = pd.DataFrame(
    data=all_datas, 
    columns=list(breast_cancer['feature_names']) + ['target'])

print(df.head(1))

NameError: name 'pd' is not defined

### P031 乳腺癌数据集 - 拆分训练集和测试集

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
data.shape

(569, 30)

In [19]:
target.shape

(569,)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    data, target, random_state=40, test_size=0.25)

In [21]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((426, 30), (426,), (143, 30), (143,))

### P032 乳腺癌数据集 - 训练测试集数据分布

In [22]:
target.shape, y_train.shape, y_test.shape

((569,), (426,), (143,))

In [23]:
for name, array in zip(["target", "y_train", "y_test"], [target, y_train, y_test]):
    print(name)
    print(pd.Series(array).value_counts(normalize=True))

target
1    0.627417
0    0.372583
dtype: float64
y_train
1    0.607981
0    0.392019
dtype: float64
y_test
1    0.685315
0    0.314685
dtype: float64


### P033 乳腺癌数据集 - 训练测试集的均匀拆分

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    data, target, random_state=40, test_size=0.25, stratify=target)

In [26]:
for name, array in zip(["target", "y_train", "y_test"], [target, y_train, y_test]):
    print(name)
    print(pd.Series(array).value_counts(normalize=True))

target
1    0.627417
0    0.372583
dtype: float64
y_train
1    0.626761
0    0.373239
dtype: float64
y_test
1    0.629371
0    0.370629
dtype: float64
