### 039 数值标准化 - 读取CSV实现数值标准化

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("./p039.csv")
df

var1   var2    var3    var4     var5
0    12.47  18.60   81.09   481.9  0.09965
1    18.94  21.31  123.60  1130.0  0.09009
2    15.46  19.48  101.70   748.9  0.10920
3    12.40  17.68   81.47   467.8  0.10540
4    11.54  14.44   74.65   402.9  0.09984
..     ...    ...     ...     ...      ...
138  14.64  15.24   95.77   651.9  0.11320
139  14.45  20.22   94.49   642.7  0.09872
140  11.04  16.83   70.92   373.2  0.10770
141  19.81  22.15  130.00  1260.0  0.09831
142  10.26  12.22   65.75   321.6  0.09996

[143 rows x 5 columns]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(df)

StandardScaler()

In [5]:
df_scaled = scaler.transform(df)

In [7]:
df_scaled[:3]

array([[-0.47853809, -0.21371678, -0.45835473, -0.51137989,  0.06357125],
       [ 1.37424404,  0.38950001,  1.29239853,  1.40549685, -0.61597356],
       [ 0.37769352, -0.01783827,  0.3904579 ,  0.27832245,  0.74240524]])

### 040 数值标准化 - 训练测试集数值标准化

In [8]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [9]:
train = pd.read_csv("./p040-train.csv")
test = pd.read_csv("./p040-test.csv")

In [10]:
train.head()

var1   var2    var3    var4     var5
0  12.89  13.12   81.89   515.9  0.06955
1  13.40  20.52   88.64   556.7  0.11060
2  12.96  18.29   84.18   525.2  0.07351
3  17.75  28.03  117.30   981.6  0.09997
4  20.58  22.14  134.70  1290.0  0.09090

In [11]:
test.head()

var1   var2    var3    var4     var5
0  12.47  18.60   81.09   481.9  0.09965
1  18.94  21.31  123.60  1130.0  0.09009
2  15.46  19.48  101.70   748.9  0.10920
3  12.40  17.68   81.47   467.8  0.10540
4  11.54  14.44   74.65   402.9  0.09984

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(train)

StandardScaler()

In [14]:
df_train = scaler.transform(train)
df_test = scaler.transform(test)

In [16]:
df_train[:3]

array([[-0.34913849, -1.43851335, -0.41172595, -0.39047943, -1.86366229],
       [-0.20468665,  0.31264011, -0.13367256, -0.27587995,  1.07807258],
       [-0.32931176, -0.21507235, -0.31739376, -0.36435749, -1.57987983]])

In [17]:
df_test[:3]

array([[-0.46809882, -0.14171322, -0.44468042, -0.485979  ,  0.29337107],
       [ 1.36445686,  0.49958757,  1.30643802,  1.3344113 , -0.39171992],
       [ 0.37878549,  0.06653205,  0.40430925,  0.26397349,  0.97774544]])

In [18]:
scaler.var_

array([1.24650551e+01, 1.78572684e+01, 5.89319980e+02, 1.26752058e+05,
       1.94723904e-04])

In [19]:
scaler.mean_

array([1.41226643e+01, 1.91988498e+01, 9.18850235e+01, 6.54919484e+02,
       9.55561972e-02])